# Generated by Django 5.2.1 on 2025-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_department_remove_student_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='join_date',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('active', 'Active'), ('deferred', 'Deferred'), ('readmitted', 'Readmitted'), ('graduated', 'Graduated'), ('dropped', 'Dropped Out')], default='active', max_length=20),
        ),
    ]
