# Generated by Django 5.2.1 on 2025-05-25 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_department_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
