# Generated by Django 5.2.1 on 2025-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_expires_at'),
        ('users', '0005_remove_student_join_date_remove_teacher_join_date_and_more'),
    ]

    operations = [
    ]
