# Generated by Django 5.2.1 on 2025-05-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250525_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='faculty',
        ),
    ]
