# Generated by Django 5.2.1 on 2025-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
