# Generated by Django 5.2.1 on 2025-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path_generator', '0002_learningpath_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
