# Generated by Django 5.2.1 on 2025-05-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path_generator', '0004_learningpaths_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='week_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
