# Generated by Django 5.2.1 on 2025-05-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path_generator', '0005_task_week_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning_path_generator.learningpath'),
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='content',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='isCompleted',
        ),
        migrations.DeleteModel(
            name='LearningPaths',
        ),
    ]
