# Generated by Django 5.2.1 on 2025-05-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0004_remove_student_department_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'assessment')},
        ),
    ]
