# Generated by Django 5.2.1 on 2025-05-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20),
        ),
    ]
