# Generated by Django 5.2.1 on 2025-05-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_model_answer_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
