# Generated by Django 5.2.1 on 2025-05-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forummessage',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
