# Generated by Django 5.2 on 2025-05-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('users', '0003_alter_student_dob_alter_teacher_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages_as_student', to='users.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages_as_teacher', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages_as_student', to='users.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages_as_teacher', to='users.teacher'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classrooms.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('students', models.ManyToManyField(blank=True, related_name='batches', to='users.student')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.department')),
            ],
            options={
                'unique_together': {('section', 'year', 'department')},
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='classrooms.batch'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='classrooms.batch'),
        ),
    ]
