# Generated by Django 5.0.6 on 2025-05-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_department_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='course_no',
            new_name='courseNo',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='teacher',
            new_name='creatorId',
        ),
    ]
