# Generated by Django 5.0.6 on 2025-05-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_rename_course_no_classroom_courseno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='creatorId',
            new_name='teacher',
        ),
    ]
