# Generated by Django 5.0.6 on 2025-05-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_department_created_at_department_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
    ]
