# Generated by Django 5.2 on 2025-05-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_remove_batch_students'),
        ('users', '0004_remove_student_department_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='users.student'),
        ),
    ]
