# Generated by Django 5.2.1 on 2025-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_remove_classroom_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='batch',
        ),
    ]
